Fix linking when compiling using -fsanitize= option
This is just a stopgap as the proper way would be to use something like:

	set(CMAKE_THREAD_PREFER_PTHREAD TRUE)
	set(THREADS_PREFER_PTHREAD_FLAG TRUE)
	find_package(Threads REQUIRED)

and then add to each target:

	target_link_libraries(<target-name> PRIVATE Threads::Threads)

But for some reasons this didn't work for me.

Fixes:
[506/4512] Linking CXX executable bin/WPEWebDriver
FAILED: bin/WPEWebDriver
: && /usr/lib64/ccache/c++  -fdiagnostics-color=always -Wno-expansion-to-defined -Wno-noexcept-type -Wno-maybe-uninitialized -Wwrite-strings -Wundef -Wpointer-arith -Wmissing-format-attribute -Wformat-security -Wcast-align -Wextra -Wall -ggdb -gdwarf-4 -gsplit-dwarf -fvar-tracking -O0 -fno-omit-frame-pointer -DDEBUG -pipe -fPIE -fsanitize=address -fsanitize-address-use-after-scope -fsanitize-recover=address -fstack-protector-all -Wno-class-memaccess -Woverloaded-virtual -fno-strict-aliasing -fno-exceptions -std=c++14 -fno-rtti -O2 -DNDEBUG -fvisibility=hidden -fvisibility-inlines-hidden -ffunction-sections -fdata-sections -fno-rtti  -fuse-ld=gold -Wl,--disable-new-dtags    -rdynamic Source/WebDriver/CMakeFiles/WebDriver.dir/CommandResult.cpp.o Source/WebDriver/CMakeFiles/WebDriver.dir/HTTPServer.cpp.o Source/WebDriver/CMakeFiles/WebDriver.dir/Session.cpp.o Source/WebDriver/CMakeFiles/WebDriver.dir/SessionHost.cpp.o Source/WebDriver/CMakeFiles/WebDriver.dir/WebDriverMain.cpp.o Source/WebDriver/CMakeFiles/WebDriver.dir/WebDriverService.cpp.o Source/WebDriver/CMakeFiles/WebDriver.dir/__/__/DerivedSources/WebDriver/WebDriverAtoms.cpp.o Source/WebDriver/CMakeFiles/WebDriver.dir/glib/SessionHostGlib.cpp.o Source/WebDriver/CMakeFiles/WebDriver.dir/glib/WebDriverServiceGLib.cpp.o Source/WebDriver/CMakeFiles/WebDriver.dir/soup/HTTPServerSoup.cpp.o Source/WebDriver/CMakeFiles/WebDriver.dir/wpe/WebDriverServiceWPE.cpp.o  -o bin/WPEWebDriver  lib/libWTF.a /usr/lib64/libsoup-2.4.so lib/libbmalloc.a -ldl /usr/lib64/libicudata.so /usr/lib64/libicui18n.so /usr/lib64/libicuuc.so /usr/lib64/libgio-2.0.so /usr/lib64/libgobject-2.0.so /usr/lib64/libglib-2.0.so /usr/lib64/libz.so && :
../Source/bmalloc/bmalloc/PerThread.h:96: error: undefined reference to 'pthread_getspecific'
../Source/bmalloc/bmalloc/PerThread.h:96: error: undefined reference to 'pthread_getspecific'
../Source/bmalloc/bmalloc/PerThread.h:96: error: undefined reference to 'pthread_getspecific'
../Source/bmalloc/bmalloc/PerThread.h:96: error: undefined reference to 'pthread_getspecific'
../Source/WTF/wtf/ThreadSpecific.h:269: error: undefined reference to 'pthread_setspecific'
../Source/WTF/wtf/ThreadSpecific.h:181: error: undefined reference to 'pthread_setspecific'
../Source/WTF/wtf/ThreadSpecific.h:164: error: undefined reference to 'pthread_key_create'
../Source/WTF/wtf/ThreadSpecific.h:181: error: undefined reference to 'pthread_setspecific'
../Source/WTF/wtf/ThreadSpecific.h:181: error: undefined reference to 'pthread_setspecific'
lib/libWTF.a(lib/../Source/WTF/wtf/CMakeFiles/WTF.dir/MainThread.cpp.o)(.debug_addr+0x950): error: undefined reference to 'pthread_key_create'
../Source/WTF/wtf/ThreadSpecific.h:164: error: undefined reference to 'pthread_key_create'
lib/libWTF.a(lib/../Source/WTF/wtf/CMakeFiles/WTF.dir/ParkingLot.cpp.o)(.debug_addr+0x6f0): error: undefined reference to 'pthread_key_create'
../Source/WTF/wtf/ThreadingPthreads.cpp:217: error: undefined reference to 'pthread_sigmask'
../Source/WTF/wtf/ThreadingPthreads.cpp:301: error: undefined reference to 'pthread_detach'
../Source/WTF/wtf/ThreadingPthreads.cpp:330: error: undefined reference to 'pthread_kill'
../Source/WTF/wtf/ThreadingPthreads.cpp:388: error: undefined reference to 'pthread_kill'
../Source/WTF/wtf/ThreadingPthreads.cpp:360: error: undefined reference to 'pthread_kill'
../Source/WTF/wtf/ThreadingPthreads.cpp:509: error: undefined reference to 'pthread_mutexattr_init'
../Source/WTF/wtf/ThreadingPthreads.cpp:510: error: undefined reference to 'pthread_mutexattr_settype'
../Source/WTF/wtf/ThreadingPthreads.cpp:515: error: undefined reference to 'pthread_mutexattr_destroy'
../Source/WTF/wtf/ThreadingPthreads.cpp:532: error: undefined reference to 'pthread_mutex_trylock'
lib/libWTF.a(lib/../Source/WTF/wtf/CMakeFiles/WTF.dir/ThreadingPthreads.cpp.o)(.debug_addr+0x378): error: undefined reference to 'pthread_mutexattr_settype'
lib/libWTF.a(lib/../Source/WTF/wtf/CMakeFiles/WTF.dir/ThreadingPthreads.cpp.o)(.debug_addr+0x4e0): error: undefined reference to 'pthread_sigmask'
lib/libWTF.a(lib/../Source/WTF/wtf/CMakeFiles/WTF.dir/ThreadingPthreads.cpp.o)(.debug_addr+0x6d0): error: undefined reference to 'pthread_mutexattr_destroy'
lib/libWTF.a(lib/../Source/WTF/wtf/CMakeFiles/WTF.dir/ThreadingPthreads.cpp.o)(.debug_addr+0xfd0): error: undefined reference to 'pthread_mutexattr_init'
lib/libWTF.a(lib/../Source/WTF/wtf/CMakeFiles/WTF.dir/ThreadingPthreads.cpp.o)(.debug_addr+0x1470): error: undefined reference to 'pthread_detach'
lib/libWTF.a(lib/../Source/WTF/wtf/CMakeFiles/WTF.dir/ThreadingPthreads.cpp.o)(.debug_addr+0x1888): error: undefined reference to 'pthread_kill'
lib/libWTF.a(lib/../Source/WTF/wtf/CMakeFiles/WTF.dir/ThreadingPthreads.cpp.o)(.debug_addr+0x1ce8): error: undefined reference to 'pthread_mutex_trylock'
../Source/WTF/wtf/StackBounds.cpp:101: error: undefined reference to 'pthread_getattr_np'
lib/libWTF.a(lib/../Source/WTF/wtf/CMakeFiles/WTF.dir/StackBounds.cpp.o)(.debug_addr+0x20): error: undefined reference to 'pthread_getattr_np'
collect2: error: ld returned 1 exit status

It's just log excerpt as the same happens for all executables.